---
#vars file
jenkins_plugins:
        - nodejs
        - ansible
        - cloudbess-folder
        - antisamy-markup-formatter
        - build-name-setter
        - build-timeout
        - config-file-provider
        - credentials-binding
        - embeddable-build-status
        - dashboard-view
        - rebuild
        - ssh-agent
        - throttle-concurrents
        - timestamper
        - ws-cleanup
        - ant
        - gradle
        - msbuild
        - nodejs
        - checkstyle
        - cobertura
        - htmlpublisher
        - junit
        - warnings
        - xunit
        - workflow-aggregator
        - github-organization-folder
        - pipeline-stage-view
        - build-pipeline-plugin
        - conditional-buildstep
        - jenkins-multijob-plugin
        - parameterized-trigger
        - copyartifact
        - bitbucket
        - clearcase
        - cvs
        - git
        - git-parameter
        - github
        - github-branch-source
        - gitlab-plugin
        - p4
        - repo
        - subversion
        - teamconcert
        - tfs
        - matrix-project
        - ssh-slavess
        - windows-slaves
        - matrix-auth
        - pam-auth
        - ldap
        - role-strategy
        - active-directory
        - email-ext
        - emailext-template
        - mailer
        - publish-over-ssh
        - ssh
        - blueocean
        - anchore-container-scanner
        - kubernetes
        - amazon-ecs
        - test-result-analyzer
        - azure-acs
        - docker-plugin
        - docker-compose-build-step
