apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-analyst-db
  namespace: default
  labels:
    app: movie-analyst-db
spec:
  replicas: 3
  minReadySeconds: 45
  selector:
    matchLabels:
      app: movie-analyst-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: movie-analyst-db
    spec:
      containers:
        - image: miguelisaza95/movie-analyst-db:0.0.2
          imagePullPolicy: IfNotPresent
          name: movie-analyst-db
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 125m
              memory: 120Mi
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name:  mysql-persistent-storage
          hostPath:
            path:  /var/lib/mysql
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
