apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-analyst-api
  namespace: default
  labels:
    app: movie-analyst-api
spec:
  replicas: {{ .Values.back.replicas }}
  minReadySeconds: 45
  selector:
    matchLabels:
      app: movie-analyst-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: movie-analyst-api
    spec:
      containers:
        - image: {{ .Values.back.image }}:{{ .Values.back.version }}
          imagePullPolicy: IfNotPresent
          name: movie-analyst-api
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: {{ .Values.database.endpoint }}
