apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-analyst-ui
  namespace: default
  labels:
    app: movie-analyst-ui
spec:
  replicas: {{ .Values.front.replicas }}
  minReadySeconds: 45
  selector:
    matchLabels:
      app: movie-analyst-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: movie-analyst-ui
    spec:
      containers:
        - image: {{ .Values.front.image }}:{{ .Values.front.version }}
          imagePullPolicy: IfNotPresent
          name: movie-analyst-ui
          ports:
            - containerPort: 3030
