# API service
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    apps: movie-analyst-api
  name: movie-analyst-api
  namespace: default
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: movie-analyst-api
  sessionAffinity: None