---
# tasks file
- name: install packages to allow apt to use repository over HTTPS
  apt:
          name:
                  - apt-transport-https
                  - ca-certificates
                  - curl
                  - gnupg-agent
                  - software-properties-common
          update_cache: yes

- name: add docker engine official gpg key
  apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

- name: see Linux Standard Base to add docker repo
  command: lsb_release -cs
  register: lsb_release

- name: see register result
  debug:
          msg: "the lsb for this instance is: {{ lsb_release.stdout }}"

- name: setting up a stable repository
  apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable
          state: present
          update_cache: yes

- name: install the latest docker engine community
  apt:
          name:
                  - docker-ce
                  - docker-ce-cli
                  - containerd.io
          state: latest

- name: install docker-compose
  shell: |
          curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  args:
          warn: no

- name: add docker-compose permission
  file:
          path: /usr/local/bin/docker-compose
          mode: u+x,g+x,o+x

- name: check docker-composer version
  command: docker-compose --version
  register: compose_version

- name: checking the version of docker-compose
  debug:
          var: compose_version.stdout

- name: add user to docker group
  user:
          name: "{{ item }}"
          group: docker
          append: true
  with_items:
          - jenkins
          - ubuntu
